// Generated by agskmem install omp-plugin. Do not edit by hand.
// agskmem-plugin-version: __PLUGIN_VERSION__

const CONFIG = {
  agskmemBin: process.env.AGSKMEM_BIN || "__AGSKMEM_BIN__",
  autoRecall: process.env.AGSKMEM_OMP_AUTO_RECALL !== "0",
  autoRetain: process.env.AGSKMEM_OMP_AUTO_RETAIN === "1",
  recallLimit: Number(process.env.AGSKMEM_OMP_RECALL_LIMIT || 10),
  blockRawMcpWrites: process.env.AGSKMEM_OMP_BLOCK_RAW_MCP_WRITES !== "0",
};

const FORBIDDEN_KEYS = {
  embedding: true,
  embeddings: true,
  embedding_vector: true,
  vector: true,
  vectors: true,
  vec: true,
  dense: true,
  sparse: true,
  colbert: true,
};

const MEMORY_KINDS = ["Decision", "Pattern", "Preference", "Style", "Habit", "Insight", "Context", "Statement"];
const RELATION_TYPES = [
  "RELATES_TO",
  "LEADS_TO",
  "OCCURRED_BEFORE",
  "PREFERS_OVER",
  "EXEMPLIFIES",
  "CONTRADICTS",
  "REINFORCES",
  "INVALIDATED_BY",
  "EVOLVED_INTO",
  "DERIVED_FROM",
  "PART_OF",
];
const RAW_WRITE_TOOLS = {
  mcp__agskmem_store_memory: true,
  mcp__agskmem_update_memory: true,
  mcp__agskmem_delete_memory: true,
  mcp__agskmem_associate_memories: true,
};

export default function agskmemExtension(pi) {
  const { z } = pi.zod;
  let startupInjected = false;
  let turnCount = 0;

  pi.setLabel("agskmem");

  function rejectForbiddenKeys(value, path = "$") {
    if (Array.isArray(value)) {
      for (let index = 0; index < value.length; index += 1) {
        rejectForbiddenKeys(value[index], `${path}[${index}]`);
      }
      return;
    }
    if (!value || typeof value !== "object") return;
    for (const [key, child] of Object.entries(value)) {
      if (FORBIDDEN_KEYS[key.toLowerCase()]) {
        throw new Error(`Forbidden memory field ${path}.${key}; agskmem generates embeddings server-side.`);
      }
      rejectForbiddenKeys(child, `${path}.${key}`);
    }
  }

  function hasDurableContent(text) {
    const normalized = text.trim().toLowerCase();
    if (!normalized) return false;
    if (normalized.length < 8) return false;
    const transient = ["todo", "to do", "plan:", "next step", "session summary", "scratch", "temporary note"];
    return !transient.some((needle) => normalized.includes(needle));
  }

  function toolText(value) {
    if (typeof value === "string") return value;
    if (value && typeof value.results_text === "string") return value.results_text;
    return JSON.stringify(value, null, 2);
  }

  function toolResult(value) {
    return { content: [{ type: "text", text: toolText(value) }], details: value };
  }

  function toolError(message, details) {
    return { content: [{ type: "text", text: message }], details, isError: true };
  }

  async function callAgskmem(ctx, toolName, args, signal) {
    rejectForbiddenKeys(args);
    const result = await pi.exec(CONFIG.agskmemBin, ["tool", toolName, JSON.stringify(args)], {
      cwd: ctx?.cwd,
      signal,
      timeout: 120000,
    });
    if (result.code !== 0) {
      const output = [result.stderr, result.stdout].filter(Boolean).join("\n").trim();
      throw new Error(output || `agskmem ${toolName} failed with exit code ${result.code}`);
    }
    try {
      return JSON.parse(result.stdout || "{}");
    } catch (error) {
      throw new Error(`agskmem ${toolName} returned invalid JSON: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  function clampLimit(value, fallback, max) {
    if (value === undefined || value === null) return fallback;
    const number = Number(value);
    if (!Number.isFinite(number)) return fallback;
    return Math.max(1, Math.min(max, Math.trunc(number)));
  }

  function compactStartupText(response) {
    const text = typeof response?.results_text === "string" ? response.results_text.trim() : "";
    if (!text) return "";
    return `<agskmem>\nRelevant durable memory from agskmem:\n${text}\n</agskmem>`;
  }

  async function startupMessage(ctx, signal) {
    if (!CONFIG.autoRecall || startupInjected) return undefined;
    startupInjected = true;
    const response = await callAgskmem(ctx, "startup_recall", { limit: clampLimit(CONFIG.recallLimit, 10, 50) }, signal);
    const content = compactStartupText(response);
    if (!content) return undefined;
    return {
      customType: "agskmem-startup-recall",
      content,
      display: "agskmem startup recall",
      details: { result_count: response?.result_count ?? 0 },
    };
  }

  pi.on("before_agent_start", async (_event, ctx) => {
    const message = await startupMessage(ctx);
    return message ? { message } : undefined;
  });

  pi.on("turn_end", () => {
    turnCount += 1;
    if (turnCount >= 5) {
      turnCount = 0;
      startupInjected = false;
    }
  });

  pi.on("tool_call", async (event) => {
    if (CONFIG.blockRawMcpWrites && RAW_WRITE_TOOLS[event.toolName]) {
      return { block: true, reason: `${event.toolName} is blocked by agskmem policy; use retain or memory_edit.` };
    }
    if (event.input !== undefined) rejectForbiddenKeys(event.input);
  });

  pi.registerTool({
    name: "retain",
    label: "Retain Memory",
    description: "Store a durable user-global memory in agskmem.",
    parameters: z.object({
      content: z.string().min(1),
      summary: z.string().optional(),
      kind: z.enum(MEMORY_KINDS).optional(),
      importance: z.number().min(0).max(1).optional(),
      confidence: z.number().min(0).max(1).optional(),
      tags: z.array(z.string()).optional(),
      metadata: z.record(z.string(), z.unknown()).optional(),
      id: z.string().optional(),
      valid_from: z.string().optional(),
      valid_until: z.string().optional(),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      if (!hasDurableContent(params.content)) {
        return toolError("retain rejected content that does not look like durable memory.", { rejected: true });
      }
      const args = {
        id: params.id,
        content: params.content,
        summary: params.summary,
        type: params.kind ?? "Statement",
        importance: params.importance,
        confidence: params.confidence,
        tags: params.tags,
        metadata: params.metadata,
        t_valid: params.valid_from,
        t_invalid: params.valid_until,
        source: "omp-extension:retain",
      };
      const response = await callAgskmem(ctx, "store_memory", args, signal);
      return toolResult(response);
    },
  });

  pi.registerTool({
    name: "recall",
    label: "Recall Memory",
    description: "Retrieve user-global memories from agskmem.",
    parameters: z.object({
      query: z.string().optional(),
      memory_id: z.string().optional(),
      tags: z.array(z.string()).optional(),
      exclude_tags: z.array(z.string()).optional(),
      limit: z.number().int().min(1).max(50).optional(),
      current_only: z.boolean().optional(),
      expand_relations: z.boolean().optional(),
      relation_limit: z.number().int().min(1).max(200).optional(),
      as_of: z.string().optional(),
      start: z.string().optional(),
      end: z.string().optional(),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      const response = await callAgskmem(ctx, "recall_memory", {
        ...params,
        limit: clampLimit(params.limit, 10, 50),
        current_only: params.current_only ?? true,
        expand_relations: params.expand_relations ?? true,
        relation_limit: clampLimit(params.relation_limit, 20, 200),
      }, signal);
      return toolResult(response);
    },
  });

  pi.registerTool({
    name: "reflect",
    label: "Reflect Memory",
    description: "Review recalled memories and related graph context without LLM-side invention.",
    parameters: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(50).optional(),
      include_graph: z.boolean().optional(),
      include_trace: z.boolean().optional(),
      write_insights: z.boolean().optional(),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      const limit = clampLimit(params.limit, 12, 50);
      const recalled = await callAgskmem(ctx, params.include_trace ? "trace_recall" : "recall_memory", {
        query: params.query,
        limit,
        expand_relations: true,
        relation_limit: 50,
        expansion_limit: 100,
        auto_decompose: true,
      }, signal);
      const memories = Array.isArray(recalled?.results) ? recalled.results : Array.isArray(recalled?.trace?.results) ? recalled.trace.results : [];
      const related = [];
      if (params.include_graph ?? true) {
        for (const memory of memories.slice(0, 5)) {
          const id = memory?.id;
          if (typeof id !== "string" || id.length === 0) continue;
          related.push({
            memory_id: id,
            neighbors: await callAgskmem(ctx, "graph_neighbors", { memory_id: id, limit: 20 }, signal),
            related: await callAgskmem(ctx, "get_related_memories", { memory_id: id, limit: 20 }, signal),
          });
        }
      }
      const packet = {
        query: params.query,
        directly_recalled: recalled,
        related_memories: related,
        write_insights: false,
        note: params.write_insights ? "write_insights is intentionally not automatic; call retain with a directly supported insight and provenance ids." : undefined,
        edit_guidance: "Use exact memory ids from this packet with memory_edit for corrections, invalidations, deletes, or relations.",
      };
      return toolResult(packet);
    },
  });

  pi.registerTool({
    name: "memory_edit",
    label: "Edit Memory",
    description: "Update, delete, invalidate, or relate agskmem memories by explicit id.",
    parameters: z.object({
      action: z.enum(["update", "delete", "relate", "invalidate"]),
      memory_id: z.string().optional(),
      memory1_id: z.string().optional(),
      memory2_id: z.string().optional(),
      content: z.string().optional(),
      summary: z.string().optional(),
      kind: z.enum(MEMORY_KINDS).optional(),
      importance: z.number().min(0).max(1).optional(),
      confidence: z.number().min(0).max(1).optional(),
      relevance: z.number().min(0).max(1).optional(),
      reliability: z.number().min(0).max(1).optional(),
      tags: z.array(z.string()).optional(),
      metadata: z.record(z.string(), z.unknown()).optional(),
      relation_type: z.enum(RELATION_TYPES).optional(),
      strength: z.number().min(0).max(1).optional(),
      reason: z.string().optional(),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      if (params.action === "relate") {
        if (!params.memory1_id || !params.memory2_id || !params.relation_type) {
          return toolError("memory_edit relate requires memory1_id, memory2_id, and relation_type.", { rejected: true });
        }
        const response = await callAgskmem(ctx, "associate_memories", {
          memory1_id: params.memory1_id,
          memory2_id: params.memory2_id,
          type: params.relation_type,
          strength: params.strength,
          confidence: params.confidence,
          metadata: params.metadata ?? (params.reason ? { reason: params.reason } : undefined),
        }, signal);
        return toolResult(response);
      }
      if (!params.memory_id) {
        return toolError(`memory_edit ${params.action} requires memory_id.`, { rejected: true });
      }
      if (params.action === "delete") {
        const response = await callAgskmem(ctx, "delete_memory", { memory_id: params.memory_id }, signal);
        return toolResult(response);
      }
      const args = {
        memory_id: params.memory_id,
        content: params.content,
        summary: params.summary,
        type: params.kind,
        importance: params.importance,
        confidence: params.confidence,
        relevance: params.relevance,
        reliability: params.reliability,
        tags: params.tags,
        metadata: params.metadata,
        archived: params.action === "invalidate" ? true : undefined,
        t_invalid: params.action === "invalidate" ? new Date().toISOString() : undefined,
      };
      const response = await callAgskmem(ctx, "update_memory", args, signal);
      return toolResult(response);
    },
  });

  pi.registerCommand("agskmem", {
    description: "agskmem stats, graph, repair, consolidate, recall, or doctor",
    handler: async (args, ctx) => {
      const [command, ...rest] = String(args || "").trim().split(/\s+/).filter(Boolean);
      if (!command || command === "stats") {
        const [stats, graph, enrichment] = await Promise.all([
          callAgskmem(ctx, "analyze_memories", {}, undefined),
          callAgskmem(ctx, "graph_stats", {}, undefined),
          callAgskmem(ctx, "enrichment_status", {}, undefined),
        ]);
        ctx.ui.notify(JSON.stringify({ stats, graph, enrichment }, null, 2), "info");
        return;
      }
      if (command === "graph") {
        ctx.ui.notify(JSON.stringify(await callAgskmem(ctx, "graph_stats", {}, undefined), null, 2), "info");
        return;
      }
      if (command === "repair") {
        ctx.ui.notify(JSON.stringify(await callAgskmem(ctx, "repair_index", {}, undefined), null, 2), "info");
        return;
      }
      if (command === "consolidate") {
        const dry_run = rest[0] !== "run";
        ctx.ui.notify(JSON.stringify(await callAgskmem(ctx, "consolidate", { mode: "all", dry_run }, undefined), null, 2), "info");
        return;
      }
      if (command === "recall") {
        ctx.ui.notify(toolText(await callAgskmem(ctx, "recall_memory", { query: rest.join(" "), limit: 10 }, undefined)), "info");
        return;
      }
      if (command === "doctor") {
        const [health, graph, enrichment] = await Promise.all([
          callAgskmem(ctx, "check_database_health", {}, undefined),
          callAgskmem(ctx, "graph_stats", {}, undefined),
          callAgskmem(ctx, "enrichment_status", {}, undefined),
        ]);
        ctx.ui.notify(JSON.stringify({ health, graph, enrichment }, null, 2), "info");
        return;
      }
      ctx.ui.notify("Usage: /agskmem stats|graph|repair|consolidate [dry-run|run]|recall <query>|doctor", "warn");
    },
  });
}
